language: android
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_64bf13095d6f_key -iv $encrypted_64bf13095d6f_iv
  -in rajawali_secret.gpg.enc -out rajawali_secret.gpg -d
- chmod +x gradlew
jdk:
- oraclejdk7
android:
  components:
  - tools
  - ndk
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
script:
- echo "Travis branch is $TRAVIS_BRANCH"
- echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
- echo "Travis tag $TRAVIS_TAG"
- echo -e "signing.keyId=${SIGNING_KEY}" >> "gradle.properties"
- echo -e "signing.password=${SIGNING_KEY_PASSWORD}" >> "gradle.properties"
- echo -e "signing.secretKeyRingFile=../rajawali_secret.gpg" >> "gradle.properties"
- echo -e $("ndk.dir=")$(pwd)$(echo "/android-ndk-r10d") >> "local.properties"
- cat local.properties
- gradle clean lint assemble uploadArchives --stacktrace --continue
install:
# Get Android NDK
- wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin
- chmod a+x ndk.bin
- ./ndk.bin 1> /dev/null 2>&1
- chmod a+x ./android-ndk-r10d/ndk-build
notifications:
  email:
  - info@rozengain.com
  - rajawali.framework@gmail.com
  - jwoolston@tenkiv.com
